#!/usr/bin/env python
#
# Wrapper script to start a sK1 application
#
# Copyright (C) 2007-2015 Igor E. Novikov
#
# This library is covered by GNU Library General Public License.
# For more info see COPYRIGHTS file in sK1 root directory.

import sys

sys.path.insert(1, '/usr/lib/sk1-tk-0.9.3')

from sk1 import sk1_run
sk1_run()
